# Generated by Django 6.0.7 on 2026-08-17 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('birthday', 'Birthday 🎂'), ('trip', 'Trip ✈️'), ('exam', 'Exam 📚'), ('meeting', 'Meeting 💼'), ('launch', 'Product Launch 🚀'), ('holiday', 'Holiday 🌴'), ('anniversary', 'Anniversary ❤️'), ('other', 'Other 🎯')], default='other', max_length=30)),
                ('color', models.CharField(default='#6366f1', max_length=30)),
                ('target_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
    ]
